/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ElearningDevelopmentRouteImport } from './routes/elearning-development'
import { Route as ElearningDevelopmentIndexRouteImport } from './routes/elearning-development.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ElearningDevelopmentRoute = ElearningDevelopmentRouteImport.update({
  id: '/elearning-development',
  path: '/elearning-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ElearningDevelopmentIndexRoute =
  ElearningDevelopmentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ElearningDevelopmentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/elearning-development': typeof ElearningDevelopmentRouteWithChildren
  '/elearning-development/': typeof ElearningDevelopmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/elearning-development': typeof ElearningDevelopmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/elearning-development': typeof ElearningDevelopmentRouteWithChildren
  '/elearning-development/': typeof ElearningDevelopmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/contact' | '/elearning-development' | '/elearning-development/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/elearning-development'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/elearning-development'
    | '/elearning-development/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ElearningDevelopmentRoute: typeof ElearningDevelopmentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elearning-development': {
      id: '/elearning-development'
      path: '/elearning-development'
      fullPath: '/elearning-development'
      preLoaderRoute: typeof ElearningDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elearning-development/': {
      id: '/elearning-development/'
      path: '/'
      fullPath: '/elearning-development/'
      preLoaderRoute: typeof ElearningDevelopmentIndexRouteImport
      parentRoute: typeof ElearningDevelopmentRoute
    }
  }
}

interface ElearningDevelopmentRouteChildren {
  ElearningDevelopmentIndexRoute: typeof ElearningDevelopmentIndexRoute
}

const ElearningDevelopmentRouteChildren: ElearningDevelopmentRouteChildren = {
  ElearningDevelopmentIndexRoute: ElearningDevelopmentIndexRoute,
}

const ElearningDevelopmentRouteWithChildren =
  ElearningDevelopmentRoute._addFileChildren(ElearningDevelopmentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ElearningDevelopmentRoute: ElearningDevelopmentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
